/**
 * 귓속말 페이지의 트리 노드.
 * 루트에서 갈라진 스물아홉 번째 가지(앞무대와 뒷무대 사이)다.
 */

import { ROOT_ID } from '../../core/tree';
import type { PageNode } from '../../core/tree';
import { whisperDictionary } from './dictionary';

export const whisperNode: PageNode = {
  id: 'backchannel-moderation',
  slug: 'whisper',
  parentId: ROOT_ID,
  title: {
    ko: whisperDictionary.ko.title,
    en: whisperDictionary.en.title,
    ja: whisperDictionary.ja.title,
  },
  summary: {
    ko: whisperDictionary.ko.summary,
    en: whisperDictionary.en.summary,
    ja: whisperDictionary.ja.summary,
  },
  capability: {
    ko: whisperDictionary.ko.capability,
    en: whisperDictionary.en.capability,
    ja: whisperDictionary.ja.capability,
  },
  look: 'hush',
  keywords: [
    '조정', '운영', '커뮤니티', '귓속말', '넛지', '디스코드', '뒷무대',
    'moderation', 'community', 'nudge', 'backchannel', 'discord', 'moderator',
    'モデレーション', 'コミュニティ', '舞台裏',
  ],
  traits: {
    domain: ['design', 'game', 'ai'],
    audience: ['professional', 'general'],
    intent: ['teach', 'inform', 'entertain'],
    stance: ['earnest'],
    atmosphere: ['serene', 'urban'],
    temperature: ['cool'],
    brightness: ['dim'],
    intensity: ['restrained'],
    tension: ['calm'],
    daytime: ['night'],
    layout: ['single-column'],
    density: ['comfortable'],
    rhythm: ['modular'],
    alignment: ['left'],
    grid: ['col-12'],
    corner: ['rounded'],
    border: ['hairline'],
    elevation: ['subtle'],
    surface: ['plain'],
    'type-voice': ['grotesk'],
    'type-scale': ['minor-third'],
    'type-contrast': ['strong'],
    tracking: ['normal'],
    leading: ['normal'],
    casing: ['sentence'],
    'motion-character': ['subtle-fade'],
    'motion-duration': ['quick'],
    easing: ['ease-out'],
    entrance: ['fade'],
    paradigm: ['direct-manipulation'],
    navigation: ['tree', 'breadcrumb'],
    feedback: ['responsive'],
    persistence: ['none'],
    tone: ['warm', 'technical'],
    person: ['second'],
    'copy-length': ['medium'],
    jargon: ['explained'],
    'data-presence': ['central'],
    imagery: ['diagram'],
    ornament: ['rule-lines'],
    'number-format': ['tabular'],
    'render-mode': ['client'],
    'compute-budget': ['zero'],
    'llm-usage': ['none'],
    'state-scope': ['stateless'],
    offline: ['full'],
    'contrast-policy': ['apca-body', 'wcag-aa'],
    'motion-policy': ['respect-reduced'],
    'focus-style': ['ring'],
  },
};
