/**
 * 물렁함 착시 페이지의 트리 노드.
 * 루트에서 갈라진 열아홉 번째 가지(몸이 속는 자리)다.
 */

import { ROOT_ID } from '../../core/tree';
import type { PageNode } from '../../core/tree';
import { softenDictionary } from './dictionary';

export const softenNode: PageNode = {
  id: 'compliance-illusion',
  slug: 'soften',
  parentId: ROOT_ID,
  title: {
    ko: softenDictionary.ko.title,
    en: softenDictionary.en.title,
    ja: softenDictionary.ja.title,
  },
  summary: {
    ko: softenDictionary.ko.summary,
    en: softenDictionary.en.summary,
    ja: softenDictionary.ja.summary,
  },
  capability: {
    ko: softenDictionary.ko.capability,
    en: softenDictionary.en.capability,
    ja: softenDictionary.ja.capability,
  },
  look: 'ripple',
  keywords: [
    '진동', '촉각', '물렁함', '착시', '파형', '지연', '햅틱',
    'vibration', 'haptic', 'compliance', 'illusion', 'waveform', 'latency', 'touchscreen',
    '振動', '触覚', '錯覚',
  ],
  traits: {
    domain: ['science', 'design', 'hardware'],
    audience: ['general', 'professional'],
    intent: ['inform', 'teach', 'entertain'],
    stance: ['earnest'],
    atmosphere: ['futuristic', 'mysterious'],
    temperature: ['cool'],
    brightness: ['dim'],
    intensity: ['restrained'],
    tension: ['calm'],
    daytime: ['night'],
    layout: ['single-column'],
    density: ['comfortable'],
    rhythm: ['modular'],
    alignment: ['left'],
    grid: ['col-12'],
    corner: ['rounded'],
    border: ['hairline'],
    elevation: ['subtle'],
    surface: ['glass'],
    'type-voice': ['grotesk'],
    'type-scale': ['minor-third'],
    'type-contrast': ['strong'],
    tracking: ['normal'],
    leading: ['normal'],
    casing: ['sentence'],
    'motion-character': ['subtle-fade'],
    'motion-duration': ['quick'],
    easing: ['ease-out'],
    entrance: ['fade'],
    paradigm: ['direct-manipulation'],
    navigation: ['tree', 'breadcrumb'],
    feedback: ['haptic'],
    persistence: ['none'],
    tone: ['technical', 'warm'],
    person: ['second'],
    'copy-length': ['medium'],
    jargon: ['explained'],
    'data-presence': ['central'],
    imagery: ['diagram'],
    ornament: ['rule-lines'],
    'number-format': ['tabular'],
    'render-mode': ['client'],
    'compute-budget': ['zero'],
    'llm-usage': ['none'],
    'state-scope': ['stateless'],
    offline: ['full'],
    'contrast-policy': ['apca-body', 'wcag-aa'],
    'motion-policy': ['respect-reduced'],
    'focus-style': ['ring'],
  },
};
