/**
 * 그림 계획 페이지의 트리 노드.
 * 루트에서 갈라진 가지 - 질적 연구자의 도판 책상이다.
 */

import { ROOT_ID } from '../../core/tree';
import type { PageNode } from '../../core/tree';
import { figureDictionary } from './dictionary';

export const figureNode: PageNode = {
  id: 'ta-result-visualization',
  slug: 'figure',
  parentId: ROOT_ID,
  title: {
    ko: figureDictionary.ko.title,
    en: figureDictionary.en.title,
    ja: figureDictionary.ja.title,
  },
  summary: {
    ko: figureDictionary.ko.summary,
    en: figureDictionary.en.summary,
    ja: figureDictionary.ja.summary,
  },
  capability: {
    ko: figureDictionary.ko.capability,
    en: figureDictionary.en.capability,
    ja: figureDictionary.ja.capability,
  },
  look: 'plate',
  keywords: [
    '질적', '주제분석', '시각화', '그림', '표', '도해', '논문', '계획',
    'qualitative', 'thematic', 'analysis', 'visualization', 'figure', 'taxonomy', 'plan',
    '質的', '主題分析', '可視化', '図',
  ],
  traits: {
    domain: ['data', 'science', 'design'],
    audience: ['professional', 'academic'],
    intent: ['teach', 'inform'],
    stance: ['earnest'],
    atmosphere: ['austere', 'urban'],
    temperature: ['cool'],
    brightness: ['bright'],
    intensity: ['restrained'],
    tension: ['calm'],
    daytime: ['noon'],
    layout: ['split-screen'],
    density: ['comfortable'],
    rhythm: ['modular'],
    alignment: ['left'],
    grid: ['col-12'],
    corner: ['rounded'],
    border: ['hairline'],
    elevation: ['subtle'],
    surface: ['plain'],
    'type-voice': ['grotesk'],
    'type-scale': ['minor-third'],
    'type-contrast': ['strong'],
    tracking: ['normal'],
    leading: ['normal'],
    casing: ['sentence'],
    'motion-character': ['subtle-fade'],
    'motion-duration': ['quick'],
    easing: ['ease-out'],
    entrance: ['fade'],
    paradigm: ['direct-manipulation'],
    navigation: ['tree', 'breadcrumb'],
    feedback: ['responsive'],
    persistence: ['url-state'],
    tone: ['technical', 'warm'],
    person: ['second'],
    'copy-length': ['medium'],
    jargon: ['explained'],
    'data-presence': ['central'],
    imagery: ['diagram'],
    ornament: ['rule-lines'],
    'number-format': ['tabular'],
    'render-mode': ['client'],
    'compute-budget': ['zero'],
    'llm-usage': ['none'],
    'state-scope': ['stateless'],
    offline: ['full'],
    'contrast-policy': ['apca-body', 'wcag-aa'],
    'motion-policy': ['respect-reduced'],
    'focus-style': ['ring'],
  },
};
